export const locationTypeOptions = [
  { value: "physical", label: "Physical location" },
  { value: "virtual", label: "Virtual location" },
];

export const timeZoneOptions = [
  { value: "Pacific/Midway", label: "(UTC-11:00) Midway Island" },
  { value: "Pacific/Pago_Pago", label: "(UTC-11:00) Pago Pago" },
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(UTC-09:00) Alaska" },
  { value: "America/Vancouver", label: "(UTC-08:00) Vancouver" },
  {
    value: "America/Los_Angeles",
    label: "(UTC-08:00) Pacific Time (US & Canada)",
  },
  { value: "America/Tijuana", label: "(UTC-08:00) Tijuana" },
  {
    value: "America/Denver",
    label: "(UTC-07:00) Mountain Time (US & Canada)",
  },
  { value: "America/Phoenix", label: "(UTC-07:00) Arizona" },
  { value: "America/Chihuahua", label: "(UTC-07:00) Chihuahua" },
  { value: "America/Guatemala", label: "(UTC-06:00) Guatemala" },
  {
    value: "America/Chicago",
    label: "(UTC-06:00) Central Time (US & Canada)",
  },
  { value: "America/Mexico_City", label: "(UTC-06:00) Mexico City" },
  { value: "America/Regina", label: "(UTC-06:00) Saskatchewan" },
  { value: "America/Bogota", label: "(UTC-05:00) Bogota" },
  {
    value: "America/New_York",
    label: "(UTC-05:00) Eastern Time (US & Canada)",
  },
  { value: "America/Lima", label: "(UTC-05:00) Lima" },
  { value: "America/Halifax", label: "(UTC-04:00) Atlantic Time (Canada)" },
  { value: "America/Caracas", label: "(UTC-04:00) Caracas" },
  { value: "America/Santiago", label: "(UTC-04:00) Santiago" },
  { value: "America/St_Johns", label: "(UTC-03:30) Newfoundland" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "(UTC-03:00) Buenos Aires",
  },
  { value: "America/Sao_Paulo", label: "(UTC-03:00) Brasilia" },
  { value: "America/Godthab", label: "(UTC-03:00) Greenland" },
  { value: "America/Montevideo", label: "(UTC-03:00) Montevideo" },
  { value: "Atlantic/South_Georgia", label: "(UTC-02:00) Mid-Atlantic" },
  { value: "Atlantic/Azores", label: "(UTC-01:00) Azores" },
  { value: "Atlantic/Cape_Verde", label: "(UTC-01:00) Cape Verde Is." },
  { value: "Africa/Casablanca", label: "(UTC+00:00) Casablanca" },
  { value: "Europe/London", label: "(UTC+00:00) London" },
  { value: "Europe/Lisbon", label: "(UTC+00:00) Lisbon" },
  { value: "Africa/Monrovia", label: "(UTC+00:00) Monrovia" },
  { value: "Etc/UTC", label: "(UTC+00:00) UTC" },
  { value: "Europe/Belgrade", label: "(UTC+01:00) Belgrade" },
  { value: "Europe/Bratislava", label: "(UTC+01:00) Bratislava" },
  { value: "Europe/Budapest", label: "(UTC+01:00) Budapest" },
  { value: "Europe/Brussels", label: "(UTC+01:00) Brussels" },
  { value: "Europe/Copenhagen", label: "(UTC+01:00) Copenhagen" },
  { value: "Europe/Madrid", label: "(UTC+01:00) Madrid" },
  { value: "Europe/Paris", label: "(UTC+01:00) Paris" },
  { value: "Europe/Warsaw", label: "(UTC+01:00) Warsaw" },
  { value: "Africa/Algiers", label: "(UTC+01:00) West Central Africa" },
  { value: "Europe/Amsterdam", label: "(UTC+01:00) Amsterdam" },
  { value: "Europe/Berlin", label: "(UTC+01:00) Berlin" },
  { value: "Europe/Rome", label: "(UTC+01:00) Rome" },
  { value: "Europe/Stockholm", label: "(UTC+01:00) Stockholm" },
  { value: "Europe/Vienna", label: "(UTC+01:00) Vienna" },
  { value: "Africa/Cairo", label: "(UTC+02:00) Cairo" },
  { value: "Europe/Helsinki", label: "(UTC+02:00) Helsinki" },
  { value: "Europe/Kyiv", label: "(UTC+02:00) Kyiv" },
  { value: "Europe/Riga", label: "(UTC+02:00) Riga" },
  { value: "Europe/Sofia", label: "(UTC+02:00) Sofia" },
  { value: "Europe/Tallinn", label: "(UTC+02:00) Tallinn" },
  { value: "Europe/Vilnius", label: "(UTC+02:00) Vilnius" },
  { value: "Europe/Athens", label: "(UTC+02:00) Athens" },
  { value: "Europe/Bucharest", label: "(UTC+02:00) Bucharest" },
  { value: "Africa/Harare", label: "(UTC+02:00) Harare" },
  { value: "Europe/Istanbul", label: "(UTC+03:00) Istanbul" },
  { value: "Asia/Jerusalem", label: "(UTC+02:00) Jerusalem" },
  { value: "Asia/Baghdad", label: "(UTC+03:00) Baghdad" },
  { value: "Asia/Kuwait", label: "(UTC+03:00) Kuwait" },
  { value: "Europe/Minsk", label: "(UTC+03:00) Minsk" },
  { value: "Europe/Moscow", label: "(UTC+03:00) Moscow" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) Nairobi" },
  { value: "Asia/Tehran", label: "(UTC+03:30) Tehran" },
  { value: "Asia/Dubai", label: "(UTC+04:00) Abu Dhabi" },
  { value: "Asia/Baku", label: "(UTC+04:00) Baku" },
  { value: "Asia/Yerevan", label: "(UTC+04:00) Yerevan" },
  { value: "Asia/Kabul", label: "(UTC+04:30) Kabul" },
  { value: "Asia/Yekaterinburg", label: "(UTC+05:00) Yekaterinburg" },
  { value: "Asia/Karachi", label: "(UTC+05:00) Karachi" },
  { value: "Asia/Tashkent", label: "(UTC+05:00) Tashkent" },
  { value: "Asia/Colombo", label: "(UTC+05:30) Colombo" },
  { value: "Asia/Kolkata", label: "(UTC+05:30) India Standard Time" },
  { value: "Asia/Kathmandu", label: "(UTC+05:45) Kathmandu" },
  { value: "Asia/Almaty", label: "(UTC+06:00) Almaty" },
  { value: "Asia/Dhaka", label: "(UTC+06:00) Dhaka" },
  { value: "Asia/Urumqi", label: "(UTC+06:00) Urumqi" },
  { value: "Asia/Rangoon", label: "(UTC+06:30) Yangon (Rangoon)" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) Bangkok" },
  { value: "Asia/Hanoi", label: "(UTC+07:00) Hanoi" },
  { value: "Asia/Jakarta", label: "(UTC+07:00) Jakarta" },
  { value: "Asia/Krasnoyarsk", label: "(UTC+07:00) Krasnoyarsk" },
  { value: "Asia/Shanghai", label: "(UTC+08:00) China Standard Time" },
  { value: "Asia/Chongqing", label: "(UTC+08:00) Chongqing" },
  { value: "Asia/Hong_Kong", label: "(UTC+08:00) Hong Kong" },
  { value: "Asia/Kuala_Lumpur", label: "(UTC+08:00) Kuala Lumpur" },
  { value: "Australia/Perth", label: "(UTC+08:00) Perth" },
  { value: "Asia/Singapore", label: "(UTC+08:00) Singapore" },
  { value: "Asia/Taipei", label: "(UTC+08:00) Taipei" },
  { value: "Asia/Ulaanbaatar", label: "(UTC+08:00) Ulaanbaatar" },
  { value: "Asia/Urumqi", label: "(UTC+08:00) Urumqi" },
  { value: "Asia/Irkutsk", label: "(UTC+08:00) Irkutsk" },
  { value: "Asia/Tokyo", label: "(UTC+09:00) Osaka" },
  { value: "Asia/Seoul", label: "(UTC+09:00) Seoul" },
  { value: "Asia/Tokyo", label: "(UTC+09:00) Tokyo" },
  { value: "Australia/Adelaide", label: "(UTC+09:30) Adelaide" },
  { value: "Australia/Darwin", label: "(UTC+09:30) Darwin" },
  { value: "Australia/Brisbane", label: "(UTC+10:00) Brisbane" },
  { value: "Australia/Canberra", label: "(UTC+10:00) Canberra" },
  { value: "Pacific/Guam", label: "(UTC+10:00) Guam" },
  { value: "Australia/Hobart", label: "(UTC+10:00) Hobart" },
  { value: "Australia/Melbourne", label: "(UTC+10:00) Melbourne" },
  { value: "Pacific/Port_Moresby", label: "(UTC+10:00) Port Moresby" },
  { value: "Australia/Sydney", label: "(UTC+10:00) Sydney" },
  { value: "Asia/Yakutsk", label: "(UTC+10:00) Yakutsk" },
  { value: "Asia/Vladivostok", label: "(UTC+11:00) Vladivostok" },
  { value: "Pacific/Auckland", label: "(UTC+12:00) Auckland" },
  { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji" },
  {
    value: "Pacific/Kwajalein",
    label: "(UTC+12:00) International Date Line West",
  },
  { value: "Asia/Kamchatka", label: "(UTC+12:00) Kamchatka" },
  { value: "Asia/Magadan", label: "(UTC+12:00) Magadan" },
  { value: "Pacific/Tongatapu", label: "(UTC+13:00) Nuku'alofa" },
];
