export const modules = [
  {
    name: "Dashboard",
    roles: ["admin", "master", "normal"],
    route: "/dashboard",
    icon: "dashboard",
  },
  {
    name: "Menu Management",
    roles: ["admin", "normal", "master"],
    route: "/menu",
    icon: "menu",
  },
  {
    name: "Aggregator Integrations",
    roles: ["admin", "normal", "master"],
    route: "/aggregator",
    icon: "aggregator",
  },
  {
    name: "CMS",
    roles: ["admin", "normal", "master"],
    route: "/cms",
    icon: "cms",
  },
  {
    name: "Marketing",
    roles: ["admin", "master", "normal"],
    route: "/marketing",
    icon: "marketing",
  },
  {
    name: "Reports",
    roles: ["admin", "master", "normal"],
    route: "/reports",
    icon: "reports",
  },
  {
    name: "Customers",
    roles: ["admin", "master", "normal"],
    route: "/customers",
    icon: "customers",
  },
  {
    name: "Rewards & Loyalty",
    roles: ["admin", "master", "normal"],
    route: "/rewards",
    icon: "rewards",
  },
  {
    name: "Team Management",
    roles: ["admin", "master", "normal"],
    route: "/teams",
    icon: "user",
  },
  {
    name: "Inventory",
    roles: ["admin", "master", "normal"],
    route: "/inventory",
    icon: "inventory",
  },
  {
    name: "Operations (Shifts)",
    roles: ["admin", "master", "normal"],
    route: "/operations",
    icon: "operations",
  },
  {
    name: "Market Insights",
    roles: ["admin", "master", "normal"],
    route: "/marketinginsights",
    icon: "marketinginsights",
  },
  {
    name: "Tips Management",
    roles: ["admin", "master", "normal"],
    route: "/tips",
    icon: "tips",
  },
  {
    name: "Staff Leaderboards",
    roles: ["admin", "master", "normal"],
    route: "/staff",
    icon: "staff",
  },
  {
    name: "Payment Integrations",
    roles: ["admin", "master", "normal"],
    route: "/payment",
    icon: "payment",
  },
  {
    name: "Table Reservations",
    roles: ["admin", "master", "normal"],
    route: "/table",
    icon: "table",
  },
  {
    name: "Banquet Reservations",
    roles: ["admin", "master", "normal"],
    route: "/banquet",
    icon: "banquet",
  },
  {
    name: "Catering",
    roles: ["admin", "master", "normal"],
    route: "/catering",
    icon: "catering",
  },
];
